# Generated by Django 4.1.1 on 2022-10-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("dueño_nombre", models.CharField(max_length=40)),
                ("dueño_apellido", models.CharField(max_length=40)),
                ("raza", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Animales",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=40)),
                ("telefono", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Veterinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Veterinarios",
            },
        ),
    ]
