# Generated by Django 4.1.1 on 2022-10-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Veterinaria", "0002_remove_veterinario_apellido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veterinario2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Veterinarios",
            },
        ),
    ]
