# Generated by Django 4.1.1 on 2022-10-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Veterinaria", "0003_veterinario2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Veterinario2",
        ),
        migrations.AddField(
            model_name="veterinario",
            name="apellido",
            field=models.CharField(default="a", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veterinario",
            name="matricula",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
